### ISSUE TITLE
Copyrights ? Or Credits ?

### ISSUE THREAD

**Issue by alimuqaddas** [aluxian/aluxian.com#1]
Is it completely available for me to use it ? Any copyrights on it or do you need credits for it?

**Comment by aluxian** [comment]
Hey, I added license MIT. Feel free to use it.

**Comment by alimuqaddas** [comment]
Ok thanks :) Its amazing work.
Hey i can't find the Blog part in code. Is it in any other branch?

**Comment by aluxian** [comment]
The blog is actually a publication on medium.com with a custom domain
